@file:Suppress("DEPRECATION")

package io.github.supermonster003.autojs6.plugin.compose.ui.renderer

import androidx.compose.material.icons.Icons
import androidx.compose.ui.graphics.vector.ImageVector
import org.autojs.plugin.compose.api.ComposeUiContractException
import org.autojs.plugin.compose.api.ComposeUiErrorCodes
import java.util.Locale
import androidx.compose.material.icons.automirrored.filled.*
import androidx.compose.material.icons.automirrored.outlined.*
import androidx.compose.material.icons.automirrored.rounded.*
import androidx.compose.material.icons.automirrored.sharp.*
import androidx.compose.material.icons.automirrored.twotone.*
import androidx.compose.material.icons.filled.*
import androidx.compose.material.icons.outlined.*
import androidx.compose.material.icons.rounded.*
import androidx.compose.material.icons.sharp.*
import androidx.compose.material.icons.twotone.*

/** Explicit public icons-core lookup. No reflection and no extended icon dependency. */
internal object IconCatalog {
    private val vectors: Map<String, () -> ImageVector> = linkedMapOf(
        "AutoMirrored.Filled.ArrowBack" to { Icons.AutoMirrored.Filled.ArrowBack },
        "AutoMirrored.Filled.ArrowForward" to { Icons.AutoMirrored.Filled.ArrowForward },
        "AutoMirrored.Filled.ExitToApp" to { Icons.AutoMirrored.Filled.ExitToApp },
        "AutoMirrored.Filled.KeyboardArrowLeft" to { Icons.AutoMirrored.Filled.KeyboardArrowLeft },
        "AutoMirrored.Filled.KeyboardArrowRight" to { Icons.AutoMirrored.Filled.KeyboardArrowRight },
        "AutoMirrored.Filled.List" to { Icons.AutoMirrored.Filled.List },
        "AutoMirrored.Filled.Send" to { Icons.AutoMirrored.Filled.Send },
        "AutoMirrored.Outlined.ArrowBack" to { Icons.AutoMirrored.Outlined.ArrowBack },
        "AutoMirrored.Outlined.ArrowForward" to { Icons.AutoMirrored.Outlined.ArrowForward },
        "AutoMirrored.Outlined.ExitToApp" to { Icons.AutoMirrored.Outlined.ExitToApp },
        "AutoMirrored.Outlined.KeyboardArrowLeft" to { Icons.AutoMirrored.Outlined.KeyboardArrowLeft },
        "AutoMirrored.Outlined.KeyboardArrowRight" to { Icons.AutoMirrored.Outlined.KeyboardArrowRight },
        "AutoMirrored.Outlined.List" to { Icons.AutoMirrored.Outlined.List },
        "AutoMirrored.Outlined.Send" to { Icons.AutoMirrored.Outlined.Send },
        "AutoMirrored.Rounded.ArrowBack" to { Icons.AutoMirrored.Rounded.ArrowBack },
        "AutoMirrored.Rounded.ArrowForward" to { Icons.AutoMirrored.Rounded.ArrowForward },
        "AutoMirrored.Rounded.ExitToApp" to { Icons.AutoMirrored.Rounded.ExitToApp },
        "AutoMirrored.Rounded.KeyboardArrowLeft" to { Icons.AutoMirrored.Rounded.KeyboardArrowLeft },
        "AutoMirrored.Rounded.KeyboardArrowRight" to { Icons.AutoMirrored.Rounded.KeyboardArrowRight },
        "AutoMirrored.Rounded.List" to { Icons.AutoMirrored.Rounded.List },
        "AutoMirrored.Rounded.Send" to { Icons.AutoMirrored.Rounded.Send },
        "AutoMirrored.Sharp.ArrowBack" to { Icons.AutoMirrored.Sharp.ArrowBack },
        "AutoMirrored.Sharp.ArrowForward" to { Icons.AutoMirrored.Sharp.ArrowForward },
        "AutoMirrored.Sharp.ExitToApp" to { Icons.AutoMirrored.Sharp.ExitToApp },
        "AutoMirrored.Sharp.KeyboardArrowLeft" to { Icons.AutoMirrored.Sharp.KeyboardArrowLeft },
        "AutoMirrored.Sharp.KeyboardArrowRight" to { Icons.AutoMirrored.Sharp.KeyboardArrowRight },
        "AutoMirrored.Sharp.List" to { Icons.AutoMirrored.Sharp.List },
        "AutoMirrored.Sharp.Send" to { Icons.AutoMirrored.Sharp.Send },
        "AutoMirrored.TwoTone.ArrowBack" to { Icons.AutoMirrored.TwoTone.ArrowBack },
        "AutoMirrored.TwoTone.ArrowForward" to { Icons.AutoMirrored.TwoTone.ArrowForward },
        "AutoMirrored.TwoTone.ExitToApp" to { Icons.AutoMirrored.TwoTone.ExitToApp },
        "AutoMirrored.TwoTone.KeyboardArrowLeft" to { Icons.AutoMirrored.TwoTone.KeyboardArrowLeft },
        "AutoMirrored.TwoTone.KeyboardArrowRight" to { Icons.AutoMirrored.TwoTone.KeyboardArrowRight },
        "AutoMirrored.TwoTone.List" to { Icons.AutoMirrored.TwoTone.List },
        "AutoMirrored.TwoTone.Send" to { Icons.AutoMirrored.TwoTone.Send },
        "Filled.AccountBox" to { Icons.Filled.AccountBox },
        "Filled.AccountCircle" to { Icons.Filled.AccountCircle },
        "Filled.Add" to { Icons.Filled.Add },
        "Filled.AddCircle" to { Icons.Filled.AddCircle },
        "Filled.ArrowBack" to { Icons.Filled.ArrowBack },
        "Filled.ArrowDropDown" to { Icons.Filled.ArrowDropDown },
        "Filled.ArrowForward" to { Icons.Filled.ArrowForward },
        "Filled.Build" to { Icons.Filled.Build },
        "Filled.Call" to { Icons.Filled.Call },
        "Filled.Check" to { Icons.Filled.Check },
        "Filled.CheckCircle" to { Icons.Filled.CheckCircle },
        "Filled.Clear" to { Icons.Filled.Clear },
        "Filled.Close" to { Icons.Filled.Close },
        "Filled.Create" to { Icons.Filled.Create },
        "Filled.DateRange" to { Icons.Filled.DateRange },
        "Filled.Delete" to { Icons.Filled.Delete },
        "Filled.Done" to { Icons.Filled.Done },
        "Filled.Edit" to { Icons.Filled.Edit },
        "Filled.Email" to { Icons.Filled.Email },
        "Filled.ExitToApp" to { Icons.Filled.ExitToApp },
        "Filled.Face" to { Icons.Filled.Face },
        "Filled.Favorite" to { Icons.Filled.Favorite },
        "Filled.FavoriteBorder" to { Icons.Filled.FavoriteBorder },
        "Filled.Home" to { Icons.Filled.Home },
        "Filled.Info" to { Icons.Filled.Info },
        "Filled.KeyboardArrowDown" to { Icons.Filled.KeyboardArrowDown },
        "Filled.KeyboardArrowLeft" to { Icons.Filled.KeyboardArrowLeft },
        "Filled.KeyboardArrowRight" to { Icons.Filled.KeyboardArrowRight },
        "Filled.KeyboardArrowUp" to { Icons.Filled.KeyboardArrowUp },
        "Filled.List" to { Icons.Filled.List },
        "Filled.LocationOn" to { Icons.Filled.LocationOn },
        "Filled.Lock" to { Icons.Filled.Lock },
        "Filled.MailOutline" to { Icons.Filled.MailOutline },
        "Filled.Menu" to { Icons.Filled.Menu },
        "Filled.MoreVert" to { Icons.Filled.MoreVert },
        "Filled.Notifications" to { Icons.Filled.Notifications },
        "Filled.Person" to { Icons.Filled.Person },
        "Filled.Phone" to { Icons.Filled.Phone },
        "Filled.Place" to { Icons.Filled.Place },
        "Filled.PlayArrow" to { Icons.Filled.PlayArrow },
        "Filled.Refresh" to { Icons.Filled.Refresh },
        "Filled.Search" to { Icons.Filled.Search },
        "Filled.Send" to { Icons.Filled.Send },
        "Filled.Settings" to { Icons.Filled.Settings },
        "Filled.Share" to { Icons.Filled.Share },
        "Filled.ShoppingCart" to { Icons.Filled.ShoppingCart },
        "Filled.Star" to { Icons.Filled.Star },
        "Filled.ThumbUp" to { Icons.Filled.ThumbUp },
        "Filled.Warning" to { Icons.Filled.Warning },
        "Outlined.AccountBox" to { Icons.Outlined.AccountBox },
        "Outlined.AccountCircle" to { Icons.Outlined.AccountCircle },
        "Outlined.Add" to { Icons.Outlined.Add },
        "Outlined.AddCircle" to { Icons.Outlined.AddCircle },
        "Outlined.ArrowBack" to { Icons.Outlined.ArrowBack },
        "Outlined.ArrowDropDown" to { Icons.Outlined.ArrowDropDown },
        "Outlined.ArrowForward" to { Icons.Outlined.ArrowForward },
        "Outlined.Build" to { Icons.Outlined.Build },
        "Outlined.Call" to { Icons.Outlined.Call },
        "Outlined.Check" to { Icons.Outlined.Check },
        "Outlined.CheckCircle" to { Icons.Outlined.CheckCircle },
        "Outlined.Clear" to { Icons.Outlined.Clear },
        "Outlined.Close" to { Icons.Outlined.Close },
        "Outlined.Create" to { Icons.Outlined.Create },
        "Outlined.DateRange" to { Icons.Outlined.DateRange },
        "Outlined.Delete" to { Icons.Outlined.Delete },
        "Outlined.Done" to { Icons.Outlined.Done },
        "Outlined.Edit" to { Icons.Outlined.Edit },
        "Outlined.Email" to { Icons.Outlined.Email },
        "Outlined.ExitToApp" to { Icons.Outlined.ExitToApp },
        "Outlined.Face" to { Icons.Outlined.Face },
        "Outlined.Favorite" to { Icons.Outlined.Favorite },
        "Outlined.FavoriteBorder" to { Icons.Outlined.FavoriteBorder },
        "Outlined.Home" to { Icons.Outlined.Home },
        "Outlined.Info" to { Icons.Outlined.Info },
        "Outlined.KeyboardArrowDown" to { Icons.Outlined.KeyboardArrowDown },
        "Outlined.KeyboardArrowLeft" to { Icons.Outlined.KeyboardArrowLeft },
        "Outlined.KeyboardArrowRight" to { Icons.Outlined.KeyboardArrowRight },
        "Outlined.KeyboardArrowUp" to { Icons.Outlined.KeyboardArrowUp },
        "Outlined.List" to { Icons.Outlined.List },
        "Outlined.LocationOn" to { Icons.Outlined.LocationOn },
        "Outlined.Lock" to { Icons.Outlined.Lock },
        "Outlined.MailOutline" to { Icons.Outlined.MailOutline },
        "Outlined.Menu" to { Icons.Outlined.Menu },
        "Outlined.MoreVert" to { Icons.Outlined.MoreVert },
        "Outlined.Notifications" to { Icons.Outlined.Notifications },
        "Outlined.Person" to { Icons.Outlined.Person },
        "Outlined.Phone" to { Icons.Outlined.Phone },
        "Outlined.Place" to { Icons.Outlined.Place },
        "Outlined.PlayArrow" to { Icons.Outlined.PlayArrow },
        "Outlined.Refresh" to { Icons.Outlined.Refresh },
        "Outlined.Search" to { Icons.Outlined.Search },
        "Outlined.Send" to { Icons.Outlined.Send },
        "Outlined.Settings" to { Icons.Outlined.Settings },
        "Outlined.Share" to { Icons.Outlined.Share },
        "Outlined.ShoppingCart" to { Icons.Outlined.ShoppingCart },
        "Outlined.Star" to { Icons.Outlined.Star },
        "Outlined.ThumbUp" to { Icons.Outlined.ThumbUp },
        "Outlined.Warning" to { Icons.Outlined.Warning },
        "Rounded.AccountBox" to { Icons.Rounded.AccountBox },
        "Rounded.AccountCircle" to { Icons.Rounded.AccountCircle },
        "Rounded.Add" to { Icons.Rounded.Add },
        "Rounded.AddCircle" to { Icons.Rounded.AddCircle },
        "Rounded.ArrowBack" to { Icons.Rounded.ArrowBack },
        "Rounded.ArrowDropDown" to { Icons.Rounded.ArrowDropDown },
        "Rounded.ArrowForward" to { Icons.Rounded.ArrowForward },
        "Rounded.Build" to { Icons.Rounded.Build },
        "Rounded.Call" to { Icons.Rounded.Call },
        "Rounded.Check" to { Icons.Rounded.Check },
        "Rounded.CheckCircle" to { Icons.Rounded.CheckCircle },
        "Rounded.Clear" to { Icons.Rounded.Clear },
        "Rounded.Close" to { Icons.Rounded.Close },
        "Rounded.Create" to { Icons.Rounded.Create },
        "Rounded.DateRange" to { Icons.Rounded.DateRange },
        "Rounded.Delete" to { Icons.Rounded.Delete },
        "Rounded.Done" to { Icons.Rounded.Done },
        "Rounded.Edit" to { Icons.Rounded.Edit },
        "Rounded.Email" to { Icons.Rounded.Email },
        "Rounded.ExitToApp" to { Icons.Rounded.ExitToApp },
        "Rounded.Face" to { Icons.Rounded.Face },
        "Rounded.Favorite" to { Icons.Rounded.Favorite },
        "Rounded.FavoriteBorder" to { Icons.Rounded.FavoriteBorder },
        "Rounded.Home" to { Icons.Rounded.Home },
        "Rounded.Info" to { Icons.Rounded.Info },
        "Rounded.KeyboardArrowDown" to { Icons.Rounded.KeyboardArrowDown },
        "Rounded.KeyboardArrowLeft" to { Icons.Rounded.KeyboardArrowLeft },
        "Rounded.KeyboardArrowRight" to { Icons.Rounded.KeyboardArrowRight },
        "Rounded.KeyboardArrowUp" to { Icons.Rounded.KeyboardArrowUp },
        "Rounded.List" to { Icons.Rounded.List },
        "Rounded.LocationOn" to { Icons.Rounded.LocationOn },
        "Rounded.Lock" to { Icons.Rounded.Lock },
        "Rounded.MailOutline" to { Icons.Rounded.MailOutline },
        "Rounded.Menu" to { Icons.Rounded.Menu },
        "Rounded.MoreVert" to { Icons.Rounded.MoreVert },
        "Rounded.Notifications" to { Icons.Rounded.Notifications },
        "Rounded.Person" to { Icons.Rounded.Person },
        "Rounded.Phone" to { Icons.Rounded.Phone },
        "Rounded.Place" to { Icons.Rounded.Place },
        "Rounded.PlayArrow" to { Icons.Rounded.PlayArrow },
        "Rounded.Refresh" to { Icons.Rounded.Refresh },
        "Rounded.Search" to { Icons.Rounded.Search },
        "Rounded.Send" to { Icons.Rounded.Send },
        "Rounded.Settings" to { Icons.Rounded.Settings },
        "Rounded.Share" to { Icons.Rounded.Share },
        "Rounded.ShoppingCart" to { Icons.Rounded.ShoppingCart },
        "Rounded.Star" to { Icons.Rounded.Star },
        "Rounded.ThumbUp" to { Icons.Rounded.ThumbUp },
        "Rounded.Warning" to { Icons.Rounded.Warning },
        "Sharp.AccountBox" to { Icons.Sharp.AccountBox },
        "Sharp.AccountCircle" to { Icons.Sharp.AccountCircle },
        "Sharp.Add" to { Icons.Sharp.Add },
        "Sharp.AddCircle" to { Icons.Sharp.AddCircle },
        "Sharp.ArrowBack" to { Icons.Sharp.ArrowBack },
        "Sharp.ArrowDropDown" to { Icons.Sharp.ArrowDropDown },
        "Sharp.ArrowForward" to { Icons.Sharp.ArrowForward },
        "Sharp.Build" to { Icons.Sharp.Build },
        "Sharp.Call" to { Icons.Sharp.Call },
        "Sharp.Check" to { Icons.Sharp.Check },
        "Sharp.CheckCircle" to { Icons.Sharp.CheckCircle },
        "Sharp.Clear" to { Icons.Sharp.Clear },
        "Sharp.Close" to { Icons.Sharp.Close },
        "Sharp.Create" to { Icons.Sharp.Create },
        "Sharp.DateRange" to { Icons.Sharp.DateRange },
        "Sharp.Delete" to { Icons.Sharp.Delete },
        "Sharp.Done" to { Icons.Sharp.Done },
        "Sharp.Edit" to { Icons.Sharp.Edit },
        "Sharp.Email" to { Icons.Sharp.Email },
        "Sharp.ExitToApp" to { Icons.Sharp.ExitToApp },
        "Sharp.Face" to { Icons.Sharp.Face },
        "Sharp.Favorite" to { Icons.Sharp.Favorite },
        "Sharp.FavoriteBorder" to { Icons.Sharp.FavoriteBorder },
        "Sharp.Home" to { Icons.Sharp.Home },
        "Sharp.Info" to { Icons.Sharp.Info },
        "Sharp.KeyboardArrowDown" to { Icons.Sharp.KeyboardArrowDown },
        "Sharp.KeyboardArrowLeft" to { Icons.Sharp.KeyboardArrowLeft },
        "Sharp.KeyboardArrowRight" to { Icons.Sharp.KeyboardArrowRight },
        "Sharp.KeyboardArrowUp" to { Icons.Sharp.KeyboardArrowUp },
        "Sharp.List" to { Icons.Sharp.List },
        "Sharp.LocationOn" to { Icons.Sharp.LocationOn },
        "Sharp.Lock" to { Icons.Sharp.Lock },
        "Sharp.MailOutline" to { Icons.Sharp.MailOutline },
        "Sharp.Menu" to { Icons.Sharp.Menu },
        "Sharp.MoreVert" to { Icons.Sharp.MoreVert },
        "Sharp.Notifications" to { Icons.Sharp.Notifications },
        "Sharp.Person" to { Icons.Sharp.Person },
        "Sharp.Phone" to { Icons.Sharp.Phone },
        "Sharp.Place" to { Icons.Sharp.Place },
        "Sharp.PlayArrow" to { Icons.Sharp.PlayArrow },
        "Sharp.Refresh" to { Icons.Sharp.Refresh },
        "Sharp.Search" to { Icons.Sharp.Search },
        "Sharp.Send" to { Icons.Sharp.Send },
        "Sharp.Settings" to { Icons.Sharp.Settings },
        "Sharp.Share" to { Icons.Sharp.Share },
        "Sharp.ShoppingCart" to { Icons.Sharp.ShoppingCart },
        "Sharp.Star" to { Icons.Sharp.Star },
        "Sharp.ThumbUp" to { Icons.Sharp.ThumbUp },
        "Sharp.Warning" to { Icons.Sharp.Warning },
        "TwoTone.AccountBox" to { Icons.TwoTone.AccountBox },
        "TwoTone.AccountCircle" to { Icons.TwoTone.AccountCircle },
        "TwoTone.Add" to { Icons.TwoTone.Add },
        "TwoTone.AddCircle" to { Icons.TwoTone.AddCircle },
        "TwoTone.ArrowBack" to { Icons.TwoTone.ArrowBack },
        "TwoTone.ArrowDropDown" to { Icons.TwoTone.ArrowDropDown },
        "TwoTone.ArrowForward" to { Icons.TwoTone.ArrowForward },
        "TwoTone.Build" to { Icons.TwoTone.Build },
        "TwoTone.Call" to { Icons.TwoTone.Call },
        "TwoTone.Check" to { Icons.TwoTone.Check },
        "TwoTone.CheckCircle" to { Icons.TwoTone.CheckCircle },
        "TwoTone.Clear" to { Icons.TwoTone.Clear },
        "TwoTone.Close" to { Icons.TwoTone.Close },
        "TwoTone.Create" to { Icons.TwoTone.Create },
        "TwoTone.DateRange" to { Icons.TwoTone.DateRange },
        "TwoTone.Delete" to { Icons.TwoTone.Delete },
        "TwoTone.Done" to { Icons.TwoTone.Done },
        "TwoTone.Edit" to { Icons.TwoTone.Edit },
        "TwoTone.Email" to { Icons.TwoTone.Email },
        "TwoTone.ExitToApp" to { Icons.TwoTone.ExitToApp },
        "TwoTone.Face" to { Icons.TwoTone.Face },
        "TwoTone.Favorite" to { Icons.TwoTone.Favorite },
        "TwoTone.FavoriteBorder" to { Icons.TwoTone.FavoriteBorder },
        "TwoTone.Home" to { Icons.TwoTone.Home },
        "TwoTone.Info" to { Icons.TwoTone.Info },
        "TwoTone.KeyboardArrowDown" to { Icons.TwoTone.KeyboardArrowDown },
        "TwoTone.KeyboardArrowLeft" to { Icons.TwoTone.KeyboardArrowLeft },
        "TwoTone.KeyboardArrowRight" to { Icons.TwoTone.KeyboardArrowRight },
        "TwoTone.KeyboardArrowUp" to { Icons.TwoTone.KeyboardArrowUp },
        "TwoTone.List" to { Icons.TwoTone.List },
        "TwoTone.LocationOn" to { Icons.TwoTone.LocationOn },
        "TwoTone.Lock" to { Icons.TwoTone.Lock },
        "TwoTone.MailOutline" to { Icons.TwoTone.MailOutline },
        "TwoTone.Menu" to { Icons.TwoTone.Menu },
        "TwoTone.MoreVert" to { Icons.TwoTone.MoreVert },
        "TwoTone.Notifications" to { Icons.TwoTone.Notifications },
        "TwoTone.Person" to { Icons.TwoTone.Person },
        "TwoTone.Phone" to { Icons.TwoTone.Phone },
        "TwoTone.Place" to { Icons.TwoTone.Place },
        "TwoTone.PlayArrow" to { Icons.TwoTone.PlayArrow },
        "TwoTone.Refresh" to { Icons.TwoTone.Refresh },
        "TwoTone.Search" to { Icons.TwoTone.Search },
        "TwoTone.Send" to { Icons.TwoTone.Send },
        "TwoTone.Settings" to { Icons.TwoTone.Settings },
        "TwoTone.Share" to { Icons.TwoTone.Share },
        "TwoTone.ShoppingCart" to { Icons.TwoTone.ShoppingCart },
        "TwoTone.Star" to { Icons.TwoTone.Star },
        "TwoTone.ThumbUp" to { Icons.TwoTone.ThumbUp },
        "TwoTone.Warning" to { Icons.TwoTone.Warning },
    )
    val names: Set<String> = java.util.Collections.unmodifiableSet(vectors.keys)
    private val normalized = vectors.keys.associateBy { it.lowercase(Locale.ROOT) }

    fun canonicalName(name: String): String {
        val full = if ('.' in name) name else "Filled.$name"
        return normalized[full.lowercase(Locale.ROOT)]
            ?: throw ComposeUiContractException(ComposeUiErrorCodes.INVALID_ARGUMENT, "Unknown icons-core name")
    }
    fun vector(name: String): ImageVector = vectors.getValue(canonicalName(name)).invoke()
}
